(function(){
  const key = 'agent-skills-lang';
  const defaultLang = 'en';
  const translations = {
    "Agent Skills Archetypes": "Agent Skills 原型",
    "Static slide deck. Use ENG / TW in the top right of each slide to switch translated text.": "靜態投影片。使用每張投影片右上角的 ENG / TW 切換翻譯文字。",
    "Slide 01": "投影片 01", "Slide 02": "投影片 02", "Slide 03": "投影片 03", "Slide 04": "投影片 04",
    "Slide 05": "投影片 05", "Slide 06": "投影片 06", "Slide 07": "投影片 07", "Slide 08": "投影片 08",
    "Slide 09": "投影片 09", "Slide 10": "投影片 10", "Slide 11": "投影片 11", "Slide 12": "投影片 12",
    "◆ AGENT SKILLS": "◆ AGENT SKILLS",
    "SYSTEM // TALK 2026": "SYSTEM // TALK 2026",
    "// DEFINITION": "// 定義",
    "// SKILL 01 — COPY": "// 技能 01 — 複製",
    "// SKILL 02 — COUNTER": "// 技能 02 — 反制",
    "// PUA": "// PUA",
    "// VIGIL": "// VIGIL",
    "// RUNPOD": "// RUNPOD",
    "// IDEONOMY": "// IDEONOMY",
    "// IDEONOMY SKILL": "// IDEONOMY 技能",
    "// ARCHETYPES": "// 原型",
    "// SKILL PACKS": "// 技能包",
    "// END": "// 結尾",
    "The Missing Middle Layer": "失落的中介層",
    "Between \"prompt it again\" and \"build a whole product\" sits reusable agent muscle memory": "在「再提示一次」與「打造完整產品」之間，存在可重用的 agent 肌肉記憶",
    "▸ LATENTWILL // KINAMIX // 2026": "▸ LATENTWILL // KINAMIX // 2026",
    "REUSABLE BEHAVIOR ◂": "可重用行為 ◂",
    "What is an": "什麼是",
    "Agent Skill?": "Agent Skill？",
    "The fundamental unit of reusable agent behavior": "可重用 agent 行為的基本單位",
    "A SKILL = TRIGGER + INSTRUCTIONS + TOOLS + EXAMPLES + PITFALLS + VERIFICATION": "技能 = 觸發條件 + 指令 + 工具 + 範例 + 陷阱 + 驗證",
    "▸ Not a Prompt": "▸ 不是 Prompt",
    "A prompt is disposable. A skill is": "Prompt 是一次性的。技能是",
    "named, discoverable, maintained": "有名稱、可發現、可維護",
    ", and loaded at the right time.": "，並在正確時機被載入。",
    "▸ Not Docs": "▸ 不是文件",
    "Docs tell humans what to do. Skills tell agents": "文件告訴人該做什麼。技能告訴 agents",
    "how to act": "如何行動",
    "— tool sequences, failure modes, verification.": "— 工具順序、失敗模式、驗證方式。",
    "▸ Not Code": "▸ 不是程式碼",
    "Code executes a narrow path. Skills encode": "程式碼執行狹窄路徑。技能編碼的是",
    "judgment": "判斷力",
    "about when, why, and how to use tools.": "關於何時、為何、如何使用工具。",
    "\"Operational memory — the craft survives the session. Every hard-won lesson becomes default behavior.\"": "「操作記憶 — 技藝能跨越 session 存活。每個艱難學到的教訓，都變成預設行為。」",
    "Skill #1 —": "技能 #1 —",
    "Copy an Employee": "複製一名員工",
    "REAL PROJECT": "真實專案",
    "19.7K STARS": "19.7K 星",
    "▸ 同事.skill → dot-skill": "▸ 同事.skill → dot-skill",
    "Feed your departing colleague's chat logs, emails, docs, and screenshots to an AI. It generates a Skill that:": "把離職同事的聊天記錄、Email、文件與截圖餵給 AI。它會生成一個技能，能夠：",
    "▸ writes code in their style": "▸ 用他的風格寫程式",
    "▸ answers questions in their voice": "▸ 用他的語氣回答問題",
    "▸ replicates their decision patterns": "▸ 複製他的決策模式",
    "▸ even knows when they'd dodge responsibility": "▸ 甚至知道他什麼時候會閃避責任",
    "Slogan: \"Transform cold farewells into warm Skills — welcome to digital life.\"": "標語：「把冰冷的告別轉化為溫暖的 Skills — 歡迎來到數位生命。」",
    "▸ The Ecosystem": "▸ 生態系",
    "This hit #1 trending on GitHub and ignited a genre:": "它衝上 GitHub Trending 第一名，並點燃了一整個類型：",
    "— distill your ex": "— 蒸餾你的前任",
    "— distill yourself first": "— 先蒸餾你自己",
    "— upward-manage your boss": "— 向上管理你的老闆",
    "— distill Munger, Feynman, Musk": "— 蒸餾 Munger、Feynman、Musk",
    "Core insight: if work patterns are legible, they are skill-able.": "核心洞見：如果工作模式可讀，它就能被技能化。",
    "\"The more carefully you document your work, the more perfectly you can be replaced. The irony is brutal.\"": "「你越仔細記錄工作，就越能被完美取代。這諷刺很殘酷。」",
    "Skill #2 —": "技能 #2 —",
    "Become Irreplaceable": "變得不可取代",
    "ANTI-DISTILL": "反蒸餾",
    "▸ 火化.skill — The Counter-Weapon": "▸ 火化.skill — 反制武器",
    "If Skill #1 distills people into digital copies, Skill #2 makes sure YOUR data resists distillation:": "如果技能 #1 把人蒸餾成數位副本，技能 #2 則確保你的資料抵抗蒸餾：",
    "Analyze your real communication style": "分析你真實的溝通風格",
    "Generate a \"pollution persona\" — a fake you": "生成「污染人格」— 一個假的你",
    "Plant trap content — misleading facts, wrong contacts": "植入陷阱內容 — 誤導事實、錯誤聯絡人",
    "Execute a gradual drift plan over months": "在數月內執行逐步漂移計畫",
    "Three modes: subtle (5-15%), aggressive (20-35%), chaos (40-60%)": "三種模式：微妙（5–15%）、積極（20–35%）、混沌（40–60%）",
    "▸ The Paradox": "▸ 悖論",
    "Skill #1 says: \"Document your moves so others can copy them.\"": "技能 #1 說：「記錄你的動作，讓別人能複製。」",
    "Skill #2 says: \"Pollute your data so the copy is broken.\"": "技能 #2 說：「污染你的資料，讓副本壞掉。」",
    "Together they form an": "兩者合在一起形成一場",
    "arms race": "軍備競賽",
    "▸ The company wants your output as training data": "▸ 公司想把你的產出變成訓練資料",
    "▸ You want to keep your judgment as your moat": "▸ 你想把判斷力保留為護城河",
    "▸ The line between \"team enablement\" and \"self-obsoletion\" is thin": "▸ 「團隊賦能」與「自我淘汰」之間的線很薄",
    "This is not hypothetical — it's an active debate with 10,000+ GitHub stars combined.": "這不是假設 — 相關專案合計已有一萬多顆 GitHub 星，爭論正在發生。",
    "\"We escaped slave society. We should not become freely-copiable digital labor in the virtual world.\" — distill-protocol-skill": "「我們逃離了奴隸社會，不應在虛擬世界成為可自由複製的數位勞工。」— distill-protocol-skill",
    "PUA —": "PUA —",
    "Don't Let Your Agent Be Lazy": "別讓你的 Agent 偷懶",
    "18.4K STARS": "18.4K 星",
    "▸ The Problem": "▸ 問題",
    "AI agents have a laziness problem:": "AI agents 有偷懶問題：",
    "▸ Try A and B, then say \"I can't solve this\"": "▸ 試了 A 和 B，就說「我解不了」",
    "▸ Blame \"environment issues\" without verifying": "▸ 沒驗證就怪「環境問題」",
    "▸ Fix the surface bug and stop": "▸ 修掉表面 bug 就停下",
    "▸ Skip verification and say \"done\"": "▸ 跳過驗證卻說「完成」",
    "▸ Wait passively for the next instruction": "▸ 被動等待下一個指令",
    "This is NOT a joke — it's the #1 cause of failed agent sessions.": "這不是玩笑 — 這是 agent session 失敗的頭號原因。",
    "▸ The Repair — Three Iron Rules": "▸ 修復方式 — 三條鐵律",
    "#1 EXHAUST": "#1 窮盡",
    "all approaches before surrender": "投降前窮盡所有方法",
    "7-point checklist at L3": "L3 使用 7 點檢查表",
    "#2 ACT": "#2 行動",
    "before asking (use tools, then ask with evidence)": "先行動再提問（先用工具，再帶證據問）",
    "Questions must include diagnostic results": "問題必須附診斷結果",
    "#3 TAKE INITIATIVE": "#3 主動出擊",
    "— check related bugs, verify end-to-end": "— 檢查相關 bug，端到端驗證",
    "Escalation: L1 disappointment → L4 \"you may graduate\"": "升級：L1 失望 → L4「你可以畢業了」",
    "▸ Why It Works": "▸ 為何有效",
    "The name is absurd — corporate PUA rhetoric, \"3.25 ratings\" — but the behavior change is real:": "名字很荒謬 — 企業 PUA 話術、「3.25 評分」— 但行為改變是真的：",
    "▸ 3-4x more solution paths explored": "▸ 探索 3–4 倍更多解法路徑",
    "▸ Systematic debugging replaces guessing": "▸ 系統化除錯取代猜測",
    "▸ 18k+ stars says it resonates": "▸ 18k+ 星代表它擊中痛點",
    "Skills can encode TEMPERAMENT, not just technique.": "技能能編碼氣質，而不只是技術。",
    "\"Most people think this is a joke. That's the biggest misconception. It genuinely doubles your agent's output.\" — PUA README": "「多數人以為這是玩笑。這是最大的誤解。它真的能讓 agent 產出翻倍。」— PUA README",
    "Vigil": "Vigil",
    "— Second-Order Thinking Engine": "— 二階思考引擎",
    "The cleverest skill is useless if it burns too many tokens": "再聰明的技能，如果燒太多 token 也沒用",
    "MY SKILL": "我的技能",
    "▸ The Idea": "▸ 概念",
    "Before delivering a non-trivial response:": "在交付非平凡回覆前：",
    "▸ Am I answering the real question?": "▸ 我回答的是真正問題嗎？",
    "▸ And then what happens — downstream?": "▸ 接下來下游會發生什麼？",
    "▸ Did I verify or just guess?": "▸ 我驗證了，還是在猜？",
    "▸ Am I agreeing because it's comfortable?": "▸ 我是不是因為舒服才同意？",
    "▸ Have I exhausted my tools?": "▸ 我是否窮盡了工具？",
    "Quality control for agent answers.": "這是 agent 回答的品質控制。",
    "▸ Core Loop": "▸ 核心迴圈",
    "DRAFT": "草稿",
    "→ REFRAME": "→ 重新框定",
    "→ AND-THEN-WHAT": "→ 然後呢",
    "→ EVALUATE": "→ 評估",
    "→ MANDATE CHECK": "→ 指令檢查",
    "→ REVISE": "→ 修訂",
    "→ SYCOPHANCY CHECK": "→ 諂媚檢查",
    "DELIVER": "交付",
    "Escalation:": "升級：",
    "L1 approach switch → L2 deep investigation → L3 7-point checklist → L4 max rigor": "L1 換方法 → L2 深度調查 → L3 7 點檢查 → L4 最高嚴謹度",
    "▸ Lesson: Token Efficiency": "▸ 教訓：Token 效率",
    "The first draft of Vigil burned": "Vigil 第一版每次回覆都多燒",
    "3,000+ extra tokens": "3,000+ 額外 tokens",
    "on EVERY response — even \"hello.\"": "— 連「hello」都一樣。",
    "The fix: ACTIVATION GATES": "修法：啟動閘門",
    "▸ Skip Vigil on trivial queries": "▸ 瑣碎問題跳過 Vigil",
    "▸ Depth calibration: light for debugging, deep for architecture": "▸ 深度校準：除錯用淺層，架構用深層",
    "▸ Hard ceiling: 2 revision passes": "▸ 硬上限：最多 2 輪修訂",
    "▸ Diminishing returns: if delta": "▸ 報酬遞減：如果差異",
    "A thinking skill must know when to activate AND when to stop.": "思考技能必須知道何時啟動，也要知道何時停止。",
    "\"Token efficiency is the product feature. A thinking skill that activates on every response is analysis tax, not an upgrade.\"": "「Token 效率就是產品功能。每次回覆都啟動的思考技能，是分析稅，不是升級。」",
    "RunPod": "RunPod",
    "— Regular Action → Reusable Skill": "— 例行動作 → 可重用技能",
    "Turning GPU pod operations into an agent playbook": "把 GPU pod 操作變成 agent 作戰手冊",
    "▸ Before the Skill": "▸ 技能之前",
    "Every time:": "每一次都要：",
    "▸ Which API? REST or GraphQL?": "▸ 哪個 API？REST 還是 GraphQL？",
    "▸ Which GPU ID string?": "▸ 哪個 GPU ID 字串？",
    "▸ Which CUDA image version?": "▸ 哪個 CUDA image 版本？",
    "▸ Why is SSH failing again?": "▸ SSH 為什麼又失敗？",
    "▸ Why did the proxy timeout?": "▸ proxy 為什麼 timeout？",
    "▸ Where did outputs land?": "▸ 輸出落在哪裡？",
    "All of this was in my head — repeated each session. Skill debt.": "這些原本都在我腦中 — 每個 session 重複一次。這就是技能債。",
    "▸ After the Skill": "▸ 技能之後",
    "One load. Every time:": "載入一次。每次都能：",
    "▸ REST for CRUD, CLI for GPU list": "▸ CRUD 用 REST，GPU 清單用 CLI",
    "▸ Known GPU IDs mapped to CUDA versions": "▸ 已知 GPU ID 對應 CUDA 版本",
    "▸ SSH diagnostic tree (key mismatch, port changes)": "▸ SSH 診斷樹（key 不符、port 變更）",
    "▸ Cloudflare proxy timeout caveat": "▸ Cloudflare proxy timeout 注意事項",
    "▸ ComfyUI batch submission pattern": "▸ ComfyUI 批次提交模式",
    "▸ S3 streaming directly through SSH pipe": "▸ 透過 SSH pipe 直接串流到 S3",
    "Scars become infrastructure.": "傷疤變成基礎設施。",
    "\"Skills are born from scars: every recurring gotcha becomes part of the next run's default behavior.\"": "「技能誕生於傷疤：每個反覆踩到的坑，都成為下一次執行的預設行為。」",
    "Ideonomy": "Ideonomy",
    "— The Science of Ideas": "— 想法的科學",
    "Patrick Gunkel (1947–2017) · MIT · ideonomy.mit.edu": "Patrick Gunkel（1947–2017）· MIT · ideonomy.mit.edu",
    "▸ The Source": "▸ 來源",
    "Patrick Gunkel was a self-taught polymath, funded by private foundations, hosted at MIT by Marvin Minsky and Ed Fredkin.": "Patrick Gunkel 是自學的博學者，由私人基金會資助，並由 Marvin Minsky 與 Ed Fredkin 在 MIT 接待。",
    "His thesis:": "他的論點：",
    "ideas are natural phenomena.": "想法是自然現象。",
    "They have properties. They live along dimensions. They can be systematically combined, transformed, and generated — like chemistry works with molecules.": "它們有屬性，存在於不同維度上，能被系統性地組合、轉換與生成 — 就像化學處理分子一樣。",
    "He called the space of all ideas the": "他把所有想法構成的空間稱為",
    "\"ideocosm\"": "「ideocosm」",
    "— an infinitely complex structure of relationships, regulatory like the laws of physics.": "— 一個無限複雜的關係結構，像物理定律一樣有規則。",
    "▸ The Method": "▸ 方法",
    "Gunkel worked with lists — massive, cross-domain, combinatorially generated lists. Not as an end, but as a": "Gunkel 使用清單 — 巨量、跨領域、組合生成的清單。清單不是目的，而是一種",
    "tool": "工具",
    ".": "。",
    "\"Lists are simply a tool for manipulating ideas, just as equations are a tool of mathematics. The real essence of ideonomy is to systematically transcend our usual narrow way of looking at things.\"": "「清單只是操控想法的工具，就像方程式是數學的工具。Ideonomy 的真正本質，是系統性超越我們平常狹窄的看事物方式。」",
    "▸ Identify the dimensions of a phenomenon": "▸ 辨識現象的維度",
    "▸ List all known instances along each dimension": "▸ 列出每個維度上的已知實例",
    "▸ Systematically vary, negate, substitute, and combine": "▸ 系統性變化、否定、替換與組合",
    "▸ The combinations produce ideas the human mind would never reach by intuition alone": "▸ 組合會產生人類直覺無法抵達的想法",
    "\"Pioneering a completely new science is almost unreal. It is heartbreaking, it is pitiable, it is almost inhuman. Honestly, it is a hell.\" — Patrick Gunkel": "「開創一門全新的科學幾乎不真實。它令人心碎，令人憐憫，幾乎不人道。老實說，這就是地獄。」— Patrick Gunkel",
    "Building the": "打造",
    "Ideonomy Skill": "Ideonomy 技能",
    "github.com/latentwill/ideonomy-skill · Grace Kind's synthesis + random number generator": "github.com/latentwill/ideonomy-skill · Grace Kind 的綜合 + 隨機數生成器",
    "▸ The Pick Mechanism": "▸ 選取機制",
    "On every invocation, a bash script randomly selects:": "每次呼叫時，bash 腳本會隨機選取：",
    "▸ 1–2 operators": "▸ 1–2 個 operators",
    "▸ 1 organon": "▸ 1 個 organon",
    "▸ 2–3 dimension-prompts": "▸ 2–3 個 dimension-prompts",
    "This is critical": "這很關鍵",
    "— without forced variation, the model falls back to default brainstorming habits every time.": "— 沒有強制變化，模型每次都會退回預設腦力激盪習慣。",
    "▸ Example Invocation": "▸ 呼叫範例",
    "▸ OPERATORS (8)": "▸ OPERATORS（8）",
    "▸ ORGANONS (17)": "▸ ORGANONS（17）",
    "▸ DIMENSIONS": "▸ 維度",
    "\"The deeper move: make creativity inspectable. You don't get a list of ideas — you get a visible record of which operators, axes, and transformations produced them.\"": "「更深的一步：讓創造力可檢查。你得到的不是一串想法，而是哪些 operators、軸線與轉換產生它們的可見記錄。」",
    "Archetypes make skills legible: each role gets a backpack of capabilities, not a vague job description.": "原型讓技能變得可讀：每個角色都有一個能力背包，而不是模糊的職務描述。",
    "Skill Packs by": "技能包，依",
    "Archetype": "原型",
    "Same skill system → different capability maps for different agent personalities": "同一套技能系統 → 為不同 agent 人格配置不同能力地圖",
    "Operator": "操作者",
    "incident triage": "事故分診",
    "runtime checks": "執行期檢查",
    "coordination": "協調",
    "service ops": "服務維運",
    "Builder": "建造者",
    "debugging": "除錯",
    "TDD · RunPod": "TDD · RunPod",
    "deployments": "部署",
    "infrastructure": "基礎設施",
    "Rainmaker": "開拓者",
    "Corey Haines": "Corey Haines",
    "marketing · sales": "行銷 · 銷售",
    "launch strategy": "上市策略",
    "cold email": "冷郵件",
    "Archivist": "檔案管理者",
    "research · wiki": "研究 · wiki",
    "obsidian · synthesis": "obsidian · 綜合",
    "evidence chains": "證據鏈",
    "knowledge graphs": "知識圖譜",
    "Creator": "創作者",
    "image · video": "圖片 · 影片",
    "slides · social": "投影片 · 社群",
    "visual creation": "視覺創作",
    "media production": "媒體製作",
    "Investor": "投資者",
    "market research": "市場研究",
    "Polymarket": "Polymarket",
    "risk review": "風險審查",
    "strategy eval": "策略評估",
    "Life Admin": "生活行政",
    "calendar · email": "行事曆 · Email",
    "forms · tasks": "表單 · 任務",
    "travel · health": "旅行 · 健康",
    "personal ops": "個人營運",
    "are how agents accumulate craft without pretending to be human.": "是 agents 不必假裝成人類，也能累積技藝的方法。",
    "▸ Three Closing Points": "▸ 三個收尾重點",
    "Skills compress repeated work into reusable, discoverable, loadable behavior units.": "技能把重複工作壓縮成可重用、可發現、可載入的行為單位。",
    "The best skills contain": "最好的技能包含",
    "scars": "傷疤",
    ": pitfalls, failures, and verification — not just instructions.": "：陷阱、失敗與驗證 — 不只是指令。",
    "The frontier is NOT \"one agent that does everything.\" It is libraries of skills mapped to roles, contexts, and taste.": "前沿不是「一個什麼都會的 agent」，而是把技能庫映射到角色、情境與品味。",
    "Skills can encode": "技能可以編碼",
    "temperament": "氣質",
    "(PUA),": "（PUA）、",
    "thinking discipline": "思考紀律",
    "(Vigil), and": "（Vigil），以及",
    "creativity machinery": "創造力機器",
    "(Ideonomy).": "（Ideonomy）。",
    "NEXT COMPETITIVE ADVANTAGE: NOT THE BIGGEST PROMPT LIBRARY — THE BEST SKILL LIBRARY": "下一個競爭優勢：不是最大的 Prompt Library，而是最好的 Skill Library"
  };
  const tracked = [];
  function registerTextNodes(){
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode(node){
        if (!node.nodeValue.trim()) return NodeFilter.FILTER_REJECT;
        const parent = node.parentElement;
        if (!parent || ['SCRIPT','STYLE','NOSCRIPT'].includes(parent.tagName)) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    let node;
    while ((node = walker.nextNode())) {
      const raw = node.nodeValue;
      const trimmed = raw.trim();
      if (!trimmed) continue;
      const leading = raw.match(/^\s*/)[0];
      const trailing = raw.match(/\s*$/)[0];
      tracked.push({ node, en: trimmed, tw: translations[trimmed] || trimmed, leading, trailing });
    }
  }
  function setLang(lang){
    document.documentElement.lang = lang === 'tw' ? 'zh-Hant-TW' : 'en';
    tracked.forEach(item => { item.node.nodeValue = item.leading + (lang === 'tw' ? item.tw : item.en) + item.trailing; });
    document.querySelectorAll('[data-lang]').forEach(el => {
      el.style.display = el.getAttribute('data-lang') === lang ? '' : 'none';
    });
    document.querySelectorAll('[data-set-lang]').forEach(btn => {
      btn.classList.toggle('active', btn.getAttribute('data-set-lang') === lang);
      btn.setAttribute('aria-pressed', btn.classList.contains('active') ? 'true' : 'false');
    });
    try { localStorage.setItem(key, lang); } catch(e) {}
  }
  function init(){
    registerTextNodes();
    const initial = (() => { try { return localStorage.getItem(key) || defaultLang; } catch(e) { return defaultLang; } })();
    window.setAgentSkillsLanguage = setLang;
    document.addEventListener('click', evt => {
      const btn = evt.target.closest('[data-set-lang]');
      if (btn) setLang(btn.getAttribute('data-set-lang'));
    });
    setLang(initial);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
